### ISSUE TITLE
text bug in custom game

### ISSUE THREAD

**Issue by Nerman8r** [will2216/Ascension-plus#12]
Thanks for making such a useful mod!  When setting the ascension above zero, the text for the modifier is printed twice with one of them offset, so it looks garbled.
![image](https://user-images.githubusercontent.com/91240821/134457474-e8adde95-05cf-4962-9462-4bbdcc9063b9.png)

**Comment by zhfy19920508** [comment]
I ended the game with all the options changed to......
And can no longer start the game properly, and flash back

java.lang.IndexOutOfBoundsException: Index: 16233, Size: 20
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.technicalpi.UI.AscModScreen.loadAscensionFromString(AscModScreen.java:869)
	at org.technicalpi.UI.AscModScreen.update(AscModScreen.java:297)
	at org.technicalpi.stspatches.AscScreenUpdateRender$Update.Postfix(AscScreenUpdateRender.java:20)
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.update(MainMenuScreen.java:298)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:789)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
